apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: static-site
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: placeholder/static-site:placeholder
          ports:
            - containerPort: 80