apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: 840986438223.dkr.ecr.ap-south-1.amazonaws.com/static-site:1.0
          ports:
            - containerPort: 80